### ISSUE TITLE
Can't paste images into Evernote

### ISSUE THREAD

**Issue by thegabrielstein** [ffMathy/Shapeshifter#466] opened 2018-05-15 02:29 UTC
**Describe the bug**
When copying images from Chrome, Control + V doesn't paste the image into an Evernote document on the desktop Evernote app.

**To Reproduce**
1. Go to Chrome
2. Copy an image directly (not the link)
3. Go to Evernote
4. Paste into a note

**Expected behavior**
It pastes the image itself from Chrome

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by KoalaBear84** [comment] 2018-05-15 04:50
Duplicate of #407 

I've changed to title to reflect the issue better.

**Closed by KoalaBear84** 2018-05-15 04:50 UTC
Labels: bug
