### ISSUE TITLE
Current install unavailable

### ISSUE THREAD

**Issue by JSebastianN** [ffMathy/Shapeshifter#4] opened 2015-07-23 10:42 UTC
Hi

The current install from http://flamefusion.net/software/shapeshifter is unavailable.

Maybe is time to make release a build here from GitHub.

I really enjoy Shapeshifter and cannot image a life without it, the far most usable Clipboard manager I know of.

**Comment by dvitonis** [comment] 2015-07-24 13:25
I'm looking forward for the release too.

**Comment by KoalaBear84** [comment] 2015-07-24 13:51
I used the old versions. And had them backupped, but I see I don't have it anymore.

I stopped using it because there were too many bugs which prevented to use it. I was in the Skype Test group that time. Unfortunately the code was not released at that time. Else I would have fixed them myself :)

I will try to get involved in the development. But for now the available code is a little too less as I don't have experience in WPF. But for the core code I will try to help to get it error free.

Problems I see now when building it is that there is nu packages.config in DesktopApplication project, missing Autofac then.

And for the rest, too many errors. I see ShapeShifter detecting the Clipboard actions. But when copying a file it gets a error that the icon (?) is not an image. And also received some out of memory error.

The thing I never found out is how to capture that the user is holding CTRL + V. Else I would have made my own simple version, probably text only.

I hope they made at least some progress last 3-4 months and not yet uploaded to GitHub.

**Comment by KoalaBear84** [comment] 2015-08-03 08:58
Looks like this is fixed. Website is accessible again :)

**Comment by ffMathy** [comment] 2015-08-04 19:35
Yes, we had some domain issues. Our domain provider was screwing around with us. Shapeshifter 4 is back online.

@KoalaBear84 would you be interested in testing version 5?

**Comment by KoalaBear84** [comment] 2015-08-04 23:12
@ffMathy Yes. Would love to. Also will try to investigate bugs when they happen.

Is there work not yet committed to GitHub?

**Comment by ffMathy** [comment] 2015-08-05 17:34
Yes, it is. And right now it also compiles and builds. Are you a developer?

**Comment by KoalaBear84** [comment] 2015-08-05 17:40
Yes. No real WPF experience, but will definitely try to help with bugs and debugging / reproducing them.

And maybe help with some small features. Hope to make some time for it.

**Comment by ffMathy** [comment] 2015-08-05 17:48
Cool! Time to learn WPF then.

I added you as a contributor to Shapeshifter. Welcome on board! Nothing is expect of you, but feel free to just go ahead and commit something.

And remember, everything can be undone later, so no need to be careful.

**Comment by ffMathy** [comment] 2015-08-05 17:49
I also advice you to load the program up, and copy some text or some files, and see how it looks.

**Comment by KoalaBear84** [comment] 2015-08-05 18:25
Thanks! Already did that with the previous version. If the absolute basics are working i will try to find / create time. With the basics I mean showing the GUI and paste (release V) something (issue you just created). The sooner the better :)

From there on I will improve and extend.

**Closed** 2015-08-10 12:16 UTC
Labels: discussion
