### ISSUE TITLE
Start error: A referral was returned from the server

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#254] opened 2018-04-23 18:36 UTC
v6.2018.0423.2167

[Window Title]
C:\Program Files\Shapeshifter\Shapeshifter.exe

[Content]
C:\Program Files\Shapeshifter\Shapeshifter.exe

A referral was returned from the server.

[OK]

**Comment by KoalaBear84** [comment] 2018-04-23 19:01
I think it should have something to do with the GitHubClient, tested it in Visual Studio, and stepped over the debug check if, and let the UpdateService do it's thing, but then there is no error. Also tried to look at it with Wireshark, but do not see traffic from api.github.com, also it is a lot harder to Wireshark with HTTPS.

**Comment by ffMathy** [comment] 2018-04-23 20:04
Use fiddler instead, it can decrypt HTTPS traffic by installing a certificate on your machine.

**Comment by ffMathy** [comment] 2018-04-24 08:16
And please share your findings here, as I can't reproduce that particular issue.

**Comment by ffMathy** [comment] 2018-04-24 10:35
I did some Googling myself. It appears that this is an AD error? Shapeshifter doesn't do anything with the active directory.

Are you running it from an AD enabled machine? Are you sure the error comes from Shapeshifter and not some anti-virus software or the like? 

Closing until I hear from you again.

**Closed by ffMathy** 2018-04-24 10:35 UTC
