### ISSUE TITLE
UnauthorizedAccessException when updating

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#108] opened 2016-01-07 08:03 UTC
I just got this when I got back at the computer. I understand this maybe is not completely tested or developed.

Just to keep this on the list:
![image](https://cloud.githubusercontent.com/assets/5886900/12165355/7aed917e-b51d-11e5-80cd-333de220a943.png)

**Comment by dvitonis** [comment] 2016-01-07 08:59
I'm getting this as well when running .exe. I'm on Windows 10.

**Comment by ffMathy** [comment] 2016-01-07 12:33
Ah, the downsides of an alpha system. I will make a unit test to test that area and get it fixed. It is actually because it calls a function that was intended to be there only for testing. Thanks for the report.

**Comment by ffMathy** [comment] 2016-01-07 16:46
#109 solves this, but it is also attempting to solve another task, and won't be closed until that task is done as well.

**Comment by ffMathy** [comment] 2016-01-07 16:50
There we go. Other than the pull request that actually fixes the bug, I have created the two issues above, which have also been marked as high priority. Combined, these should help preventing future update issues, which is important if we need to get to a Beta release.

**Comment by ffMathy** [comment] 2016-01-10 20:31
I am still on it. I have had a busy past couple of days. Also managed to turn Shapeshifter into a single executable with no DLLs, which is really cool. It is fully portable now.

**Comment by ffMathy** [comment] 2016-01-10 20:31
When the pull request gets merged, that is.

**Comment by ffMathy** [comment] 2016-01-12 07:42
Hey guys, I am now stuck. See the `develop` branch for more details. I am currently working on #38 there, and have also fixed this issue there.

However, I am having issues getting #38 done. I will post more details on that issue. I need your help to continue.

**Closed** 2016-01-13 07:32 UTC
Labels: bug, fixed
