### ISSUE TITLE
Shapeshifter process ending immediately after start

### ISSUE THREAD

**Issue by thejoshtaylor** [ffMathy/Shapeshifter#374] opened 2018-05-03 21:18 UTC
Downloaded v6.2018.429.2389 exe file and whenever I attempt to start it, the initial notification and the icon appear, but the process is ends immediately after. Attached is the .log file recorded with the issue.

[Shapeshifter20180503.log](https://github.com/ffMathy/Shapeshifter/files/1972665/Shapeshifter20180503.log)

**Comment by KoalaBear84** [comment] 2018-05-03 21:29
Duplicate of https://github.com/ffMathy/Shapeshifter/issues/345

Please download the newest version and try again. 😃

**Comment by thejoshtaylor** [comment] 2018-05-03 22:05
@KoalaBear84 Issue is still present. After deleting old Shapeshifter folders in both Program Files and Temp and redownloading the latest .exe, I still get the same issue.

**Comment by ffMathy** [comment] 2018-05-03 23:55
Will investigate!

**Comment by ffMathy** [comment] 2018-05-04 06:31
@KoalaBear84 was right. It is a duplicate. The reason you are seeing this is because you are on the latest "stable" build which has this problem, but the latest pre-release build (see "releases") has this problem fixed.

**Closed by ffMathy** 2018-05-04 06:31 UTC
