### ISSUE TITLE
Problems with Steam Client's Chat Window

### ISSUE THREAD

**Issue by Ardakilic** [ffMathy/Shapeshifter#161] opened 2016-07-13 21:57 UTC
Heya,

Firstly thank you for maintaining this app. This is quite useful!

I'm having an issue with Shapesifter 5 and 6.x with Valve's gaming platform client called Steam.

Whenever I try to paste a thing from clipboard to a Steam chat window, it just doesn't get pasted. However, right clicking and selecting "paste" item just works. 

However, I think I found an not-always-working workaround. 
I have to "ctrl+v" and release my key from "v" button before the Shapeshifter interface appears, but this doesn't work always.

I'm using Windows 10 Home edition x64.

I'd appreciate if a solution would be found for this. This is becoming quite annoying.

Thanks in advance,

**Comment by ffMathy** [comment] 2016-07-14 01:00
Thanks for your report. I think this is related to #158, but I will check it out anyway.

**Comment by ffMathy** [comment] 2016-07-14 01:22
I will download and install Steam now to see if I can confirm. Can you add me on Steam? Then I can test by writing to you.

Username is `mathiaslylo`.

**Comment by ffMathy** [comment] 2016-07-14 01:32
The problem has now been confirmed. Investigating the issue.

**Comment by ffMathy** [comment] 2016-07-14 01:46
Fixed. It seams Steam can be slow at picking up the paste keyboard hotkey that Shapeshifter sends, so I inserted a small delay.

**Comment by ffMathy** [comment] 2016-07-14 01:46
Will be released when #162 is merged.

**Comment by Ardakilic** [comment] 2016-07-14 05:55
Aha, I was not expecting a fast response and solution such as this, thanks @ffMathy ! :smile: 

I would add you, but however I was sleeping at that time. If you still need assistance, just let me know.

Cheers,

**Comment by ffMathy** [comment] 2016-07-19 21:59
This has been re-opened because the fix for it introduced #167. I have therefore reverted the fix, until we find a resolution.

**Comment by ffMathy** [comment] 2018-04-25 20:36
This has now finally been fixed.

**Closed by ffMathy** 2018-04-25 20:36 UTC
Labels: bug
