### ISSUE TITLE
Crash 6.1.1947

### ISSUE THREAD

**Issue by NoxArt** [ffMathy/Shapeshifter#181] opened 2016-08-11 08:26 UTC
Hi,
trying the new Shapes., when I download Shapeshifter.exe and run it, it crashes with following error (with or without Run as admin):

![image](https://cloud.githubusercontent.com/assets/291595/17582851/2ba7fcee-5fae-11e6-9b6a-99c40693b699.png)

Windows 10 x64
Thank you for looking into it

**Comment by nicchristeller** [comment] 2016-08-17 10:15
I am getting the same, Windows 7.

**Comment by Rotozaza** [comment] 2016-09-15 19:53
same on Windows 10 x64

**Comment by ffMathy** [comment] 2016-09-18 15:12
This is a duplicate of #180.

**Closed by ffMathy** 2016-09-18 15:12 UTC

**Comment by NoxArt** [comment] 2016-09-18 19:35
Same error with 1950
![shapeshiftererror](https://cloud.githubusercontent.com/assets/291595/18618461/92c85976-7de7-11e6-8ba1-896682d258b8.png)

Is it really a duplicate? Neither exception is the same

**Comment by ffMathy** [comment] 2016-09-18 19:38
No, but when I resolved one, I got the other. It is a follow-up error and hence should have the same resolution 😄

**Comment by NoxArt** [comment] 2016-09-18 19:57
Thank you for a quick reply. I see ... it doesn't seem to be fixed in the version uploaded 5 hours ago though, so the fix is not yet released? Otherwise it still seems to be there

**Comment by ffMathy** [comment] 2016-09-18 20:12
No, the only thing I changed 5 hours ago was a note on the front page saying we are looking for contributors (since I do not have enough time to fix all of these issues). Do you happen to be a developer?

**Comment by NoxArt** [comment] 2016-09-19 18:04
One with the same issue as you :) sorry I can't be of help...
